spring:
  datasource:
    url: jdbc:mysql://dev-db.csjr0037o5ke.ap-northeast-2.rds.amazonaws.com:3306/test?serverTimezone=Asia/Seoul
    username: admin
    password: polzzak11*
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: update
#    properties.hibernate.format_sql: true