spring:
  config:
    import:
      - classpath:/secret.yml
  activate:
    on-profile: dev

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      open-in-view: false
      ddl-auto: update