---
spring:
  config.activate.on-profile: local, dev, prod
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
---
spring:
  config.activate.on-profile: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database: h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;
