spring:
  config:
    import:
      - classpath:/secret.yml
  activate:
    on-profile: local

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      open-in-view: false
      ddl-auto: update
